"""
Database models for Kosmos AI Scientist.

Models:
- Experiment: Research experiments
- Hypothesis: Generated hypotheses
- Result: Experiment results
- Paper: Literature papers
- Agent: Agent instances
"""

from sqlalchemy import Column, String, Integer, Float, Boolean, Text, DateTime, ForeignKey, JSON, Enum as SQLEnum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import enum


Base = declarative_base()


class ExperimentStatus(str, enum.Enum):
    """Experiment status."""
    CREATED = "created"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class HypothesisStatus(str, enum.Enum):
    """Hypothesis status."""
    GENERATED = "generated"
    TESTING = "testing"
    SUPPORTED = "supported"
    REJECTED = "rejected"
    INCONCLUSIVE = "inconclusive"


class Experiment(Base):
    """
    Experiment model.

    Represents a research experiment designed to test a hypothesis.
    """
    __tablename__ = "experiments"

    id = Column(String, primary_key=True)
    hypothesis_id = Column(String, ForeignKey("hypotheses.id"), nullable=False)
    experiment_type = Column(String, nullable=False)  # computational, data_analysis, simulation
    description = Column(Text, nullable=False)
    protocol = Column(JSON, nullable=False)  # Experiment protocol details

    status = Column(SQLEnum(ExperimentStatus), default=ExperimentStatus.CREATED)
    domain = Column(String, nullable=False)  # biology, physics, etc.

    # Execution details
    code_generated = Column(Text, nullable=True)
    execution_time_seconds = Column(Float, nullable=True)
    error_message = Column(Text, nullable=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    hypothesis = relationship("Hypothesis", back_populates="experiments")
    results = relationship("Result", back_populates="experiment", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Experiment {self.id} status={self.status}>"


class Hypothesis(Base):
    """
    Hypothesis model.

    Represents a scientific hypothesis generated by the system.
    """
    __tablename__ = "hypotheses"

    id = Column(String, primary_key=True)
    research_question = Column(Text, nullable=False)
    statement = Column(Text, nullable=False)
    rationale = Column(Text, nullable=False)

    domain = Column(String, nullable=False)
    status = Column(SQLEnum(HypothesisStatus), default=HypothesisStatus.GENERATED)

    # Scoring
    novelty_score = Column(Float, nullable=True)
    testability_score = Column(Float, nullable=True)
    confidence_score = Column(Float, nullable=True)

    # Literature context
    related_papers = Column(JSON, nullable=True)  # List of paper IDs

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    experiments = relationship("Experiment", back_populates="hypothesis")

    def __repr__(self):
        return f"<Hypothesis {self.id} status={self.status}>"


class Result(Base):
    """
    Result model.

    Stores experimental results and analysis.
    """
    __tablename__ = "results"

    id = Column(String, primary_key=True)
    experiment_id = Column(String, ForeignKey("experiments.id"), nullable=False)

    # Raw results
    data = Column(JSON, nullable=False)  # Result data
    statistical_tests = Column(JSON, nullable=True)  # Statistical test results

    # Analysis
    interpretation = Column(Text, nullable=True)  # Claude's interpretation
    key_findings = Column(JSON, nullable=True)  # List of key findings
    supports_hypothesis = Column(Boolean, nullable=True)

    # Significance
    p_value = Column(Float, nullable=True)
    effect_size = Column(Float, nullable=True)
    confidence_interval = Column(JSON, nullable=True)

    # Visualization
    figures = Column(JSON, nullable=True)  # Paths to generated figures

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    experiment = relationship("Experiment", back_populates="results")

    def __repr__(self):
        return f"<Result {self.id} experiment={self.experiment_id}>"


class Paper(Base):
    """
    Paper model.

    Represents scientific literature papers.
    """
    __tablename__ = "papers"

    id = Column(String, primary_key=True)  # arXiv ID, DOI, etc.
    title = Column(String, nullable=False)
    authors = Column(JSON, nullable=False)  # List of author names
    abstract = Column(Text, nullable=False)

    # Source
    source = Column(String, nullable=False)  # arXiv, semantic scholar, pubmed
    url = Column(String, nullable=True)
    doi = Column(String, nullable=True)
    arxiv_id = Column(String, nullable=True)

    # Metadata
    publication_date = Column(DateTime, nullable=True)
    domain = Column(String, nullable=True)
    keywords = Column(JSON, nullable=True)

    # Analysis
    summary = Column(Text, nullable=True)  # AI-generated summary
    key_methods = Column(JSON, nullable=True)
    key_findings = Column(JSON, nullable=True)
    relevance_score = Column(Float, nullable=True)

    # Embeddings (for semantic search)
    embedding = Column(JSON, nullable=True)  # Vector embedding

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    analyzed_at = Column(DateTime, nullable=True)

    def __repr__(self):
        return f"<Paper {self.id}: {self.title[:50]}>"


class AgentRecord(Base):
    """
    Agent record model.

    Tracks agent instances and their state.
    """
    __tablename__ = "agents"

    id = Column(String, primary_key=True)
    agent_type = Column(String, nullable=False)
    status = Column(String, nullable=False)

    # Configuration
    config = Column(JSON, nullable=True)

    # State
    state_data = Column(JSON, nullable=True)

    # Statistics
    messages_sent = Column(Integer, default=0)
    messages_received = Column(Integer, default=0)
    tasks_completed = Column(Integer, default=0)
    errors_encountered = Column(Integer, default=0)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    stopped_at = Column(DateTime, nullable=True)

    def __repr__(self):
        return f"<Agent {self.agent_type} {self.id}>"


class ResearchSession(Base):
    """
    Research session model.

    Groups related experiments under a research session.
    """
    __tablename__ = "research_sessions"

    id = Column(String, primary_key=True)
    research_question = Column(Text, nullable=False)
    domain = Column(String, nullable=False)

    # Status
    status = Column(String, default="active")  # active, paused, completed
    iteration = Column(Integer, default=1)

    # Progress
    hypotheses_generated = Column(Integer, default=0)
    experiments_completed = Column(Integer, default=0)
    discoveries_made = Column(JSON, nullable=True)

    # Configuration
    max_iterations = Column(Integer, default=10)
    autonomous_mode = Column(Boolean, default=True)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    def __repr__(self):
        return f"<ResearchSession {self.id} iteration={self.iteration}>"
