"""initial_schema

Revision ID: 2ec489a3eb6b
Revises: 
Create Date: 2025-11-12 13:10:20.019346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec489a3eb6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('state_data', sa.JSON(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('messages_received', sa.Integer(), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), nullable=True),
    sa.Column('errors_encountered', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'TESTING', 'SUPPORTED', 'REJECTED', 'INCONCLUSIVE', name='hypothesisstatus'), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('testability_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('related_papers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('arxiv_id', sa.String(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_methods', sa.JSON(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=True),
    sa.Column('hypotheses_generated', sa.Integer(), nullable=True),
    sa.Column('experiments_completed', sa.Integer(), nullable=True),
    sa.Column('discoveries_made', sa.JSON(), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=True),
    sa.Column('autonomous_mode', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('experiment_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('protocol', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='experimentstatus'), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('code_generated', sa.Text(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('statistical_tests', sa.JSON(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('supports_hypothesis', sa.Boolean(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('figures', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('experiments')
    op.drop_table('research_sessions')
    op.drop_table('papers')
    op.drop_table('hypotheses')
    op.drop_table('agents')
    # ### end Alembic commands ###
